// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: pkg/grpc/dispatch_service/dispatchService.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DispatchServiceClient is the client API for DispatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DispatchServiceClient interface {
	SubscribeFor(ctx context.Context, in *SubscribeForRequest, opts ...grpc.CallOption) (*SubscribeForResponse, error)
	SendDispatch(ctx context.Context, in *SendDispatchRequest, opts ...grpc.CallOption) (*SendDispatchResponse, error)
	GetDispatch(ctx context.Context, in *GetDispatchRequest, opts ...grpc.CallOption) (*GetDispatchResponse, error)
}

type dispatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchServiceClient(cc grpc.ClientConnInterface) DispatchServiceClient {
	return &dispatchServiceClient{cc}
}

func (c *dispatchServiceClient) SubscribeFor(ctx context.Context, in *SubscribeForRequest, opts ...grpc.CallOption) (*SubscribeForResponse, error) {
	out := new(SubscribeForResponse)
	err := c.cc.Invoke(ctx, "/main.DispatchService/SubscribeFor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) SendDispatch(ctx context.Context, in *SendDispatchRequest, opts ...grpc.CallOption) (*SendDispatchResponse, error) {
	out := new(SendDispatchResponse)
	err := c.cc.Invoke(ctx, "/main.DispatchService/SendDispatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) GetDispatch(ctx context.Context, in *GetDispatchRequest, opts ...grpc.CallOption) (*GetDispatchResponse, error) {
	out := new(GetDispatchResponse)
	err := c.cc.Invoke(ctx, "/main.DispatchService/GetDispatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatchServiceServer is the server API for DispatchService service.
// All implementations must embed UnimplementedDispatchServiceServer
// for forward compatibility
type DispatchServiceServer interface {
	SubscribeFor(context.Context, *SubscribeForRequest) (*SubscribeForResponse, error)
	SendDispatch(context.Context, *SendDispatchRequest) (*SendDispatchResponse, error)
	GetDispatch(context.Context, *GetDispatchRequest) (*GetDispatchResponse, error)
	mustEmbedUnimplementedDispatchServiceServer()
}

// UnimplementedDispatchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDispatchServiceServer struct {
}

func (UnimplementedDispatchServiceServer) SubscribeFor(context.Context, *SubscribeForRequest) (*SubscribeForResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscribeFor not implemented")
}
func (UnimplementedDispatchServiceServer) SendDispatch(context.Context, *SendDispatchRequest) (*SendDispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDispatch not implemented")
}
func (UnimplementedDispatchServiceServer) GetDispatch(context.Context, *GetDispatchRequest) (*GetDispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDispatch not implemented")
}
func (UnimplementedDispatchServiceServer) mustEmbedUnimplementedDispatchServiceServer() {}

// UnsafeDispatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatchServiceServer will
// result in compilation errors.
type UnsafeDispatchServiceServer interface {
	mustEmbedUnimplementedDispatchServiceServer()
}

func RegisterDispatchServiceServer(s grpc.ServiceRegistrar, srv DispatchServiceServer) {
	s.RegisterService(&DispatchService_ServiceDesc, srv)
}

func _DispatchService_SubscribeFor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeForRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).SubscribeFor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.DispatchService/SubscribeFor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).SubscribeFor(ctx, req.(*SubscribeForRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_SendDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).SendDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.DispatchService/SendDispatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).SendDispatch(ctx, req.(*SendDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_GetDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).GetDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.DispatchService/GetDispatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).GetDispatch(ctx, req.(*GetDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DispatchService_ServiceDesc is the grpc.ServiceDesc for DispatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DispatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.DispatchService",
	HandlerType: (*DispatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubscribeFor",
			Handler:    _DispatchService_SubscribeFor_Handler,
		},
		{
			MethodName: "SendDispatch",
			Handler:    _DispatchService_SendDispatch_Handler,
		},
		{
			MethodName: "GetDispatch",
			Handler:    _DispatchService_GetDispatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/dispatch_service/dispatchService.proto",
}
