with-expecter: true
outpkg: mocks
dir: "internal/mocks/{{.PackageName}}"
mockname: "{{.InterfaceName}}"
packages:
  subscription-api/internal/services/currency:
    interfaces:
      CurrencyService:
  subscription-api/internal/services/dispatch:
    interfaces:
      DispatchService:
  subscription-api/internal/db:
    interfaces:
      Store:
  subscription-api/internal/db/dispatch:
    interfaces:
      DispatchStore:


